Repository linear-b/gitstream-github-action, pull requests merged in 2024-04, with the labels that each got.

#61 LINBEE-6941 Upgrade actions/checkout to v4 and actions/github-script …
  action.yml
Labels: 1 min review

#62 Linbee 6728 add option to run GitHub action with cache
  action.yml
Labels: 1 min review, 1 Unresolved Thread(s)

#63 Revert "Linbee 6728 add option to run GitHub action with cache"
  action.yml
Labels: 1 min review

#64 Add option to update Docker cache key based on the number of times th…
  action.yml
  script.js
Labels: 5 min review
